### ISSUE TITLE
Error On Mira Refresh (Macbook)

### ISSUE THREAD

**Issue by josephhsieh** [ipodnerd3019/mira-js#1]
I got following error when I ran the command: **npx mira refresh**

usr/local/lib/node_modules/boox-mira/node_modules/node-hid/nodehid.js:49
    this._raw = new (Function.prototype.bind.apply(binding.HID,
                ^

TypeError: cannot open device with vendor id 0x416 and product id 0x5020
    at new HID (/usr/local/lib/node_modules/boox-mira/node_modules/node-hid/nodehid.js:49:17)
    at Function.create (file:///usr/local/lib/node_modules/boox-mira/src/mira.js:30:20)
    at file:///usr/local/lib/node_modules/boox-mira/bin/cli.js:7:19
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)

**Comment by ipodnerd3019** [comment]
Hi Joseph, thanks for filing a bug.

`npx mira refresh` works on my macbook, so there's probably something wrong with your USB connection.

1. Are you running the official Mira driver? Only 1 driver can open the Mira device at a time
2. Please try running `ioreg -p IOUSB -l -w 0` to verify the Mira shows up. I see this entry:
```
  | | |   +-o BOOX MIRA253@14524100  <class AppleUSBDevice, id 0x100000a0d, registered, matched, active, busy 0 (1 ms), retain 11>
  | | |   |   {
  | | |   |     "sessionID" = 79594648994
  | | |   |     "idProduct" = 20512
  | | |   |     "iManufacturer" = 1
  | | |   |     "bDeviceClass" = 0
  | | |   |     "bMaxPacketSize0" = 64
  | | |   |     "bcdDevice" = 512
  | | |   |     "iProduct" = 2
  | | |   |     "iSerialNumber" = 3
  | | |   |     "bNumConfigurations" = 1
  | | |   |     "Bus Power Available" = 250
  | | |   |     "USB Address" = 10
  | | |   |     "Built-In" = No
  | | |   |     "locationID" = 340934912
  | | |   |     "bDeviceSubClass" = 0
  | | |   |     "bcdUSB" = 512
  | | |   |     "USB Product Name" = "BOOX MIRA253"
  | | |   |     "PortNum" = 1
  | | |   |     "non-removable" = "no"
  | | |   |     "kUSBSerialNumberString" = ""
  | | |   |     "bDeviceProtocol" = 0
  | | |   |     "AppleUSBAlternateServiceRegistryID" = 4294969867
  | | |   |     "IOCFPlugInTypes" = {"9dc7b780-9ec0-11d4-a54f-000a27052861"="IOUSBHostFamily.kext/Contents/PlugIns/IOUSBLib.bundle"}
  | | |   |     "IOPowerManagement" = {"DevicePowerState"=0,"CurrentPowerState"=3,"CapabilityFlags"=65536,"MaxPowerState"=4,"DriverPowerState"=3}
  | | |   |     "Device Speed" = 1
  | | |   |     "USB Vendor Name" = "ONYX"
  | | |   |     "idVendor" = 1046
  | | |   |     "kUSBCurrentConfiguration" = 1
  | | |   |     "IOGeneralInterest" = "IOCommand is not serializable"
  | | |   |     "kUSBProductString" = "BOOX MIRA253"
  | | |   |     "USB Serial Number" = ""
  | | |   |     "kUSBVendorString" = "ONYX"
  | | |   |     "IOClassNameOverride" = "IOUSBDevice"
  | | |   |   }
```
