### ISSUE TITLE
TypeError: cannot open device with vendor id 0x416 and product id 0x5020

### ISSUE THREAD

**Issue by CristianKerr** [ipodnerd3019/mira-js#2]
When I try:
`npx mira refresh`

I get:
```
/usr/lib/node_modules/boox-mira/node_modules/node-hid/nodehid.js:49
    this._raw = new (Function.prototype.bind.apply(binding.HID,
                ^

TypeError: cannot open device with vendor id 0x416 and product id 0x5020
    at new HID (/usr/lib/node_modules/boox-mira/node_modules/node-hid/nodehid.js:49:17)
    at Function.create (file:///usr/lib/node_modules/boox-mira/src/mira.js:43:20)
    at file:///usr/lib/node_modules/boox-mira/bin/cli.js:7:19
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
```
I have the Boox Mira Pro connected via HDMI cable.

`npm -v` 8.10.0
`node -v` v16.15.0

**Comment by CristianKerr** [comment]
you're right 😅 Thanks mate. Btw, is there any way to send you a little donation?

**Comment by CristianKerr** [comment]
you're right 😅 Thanks mate. Btw, is there any way to send you a little donation?

**Comment by ipodnerd3019** [comment]
Glad I could help :)

I'm not able to accept donations right now, but thanks for offering!

**Comment by bmitchinson** [comment]
Hmmm. Still getting that message despite the Mira software identifying the screen after a power cycle.

![image](https://user-images.githubusercontent.com/33632286/202871936-ffc7e369-afa8-482f-ad80-0a0177e76126.png)

**Comment by mkmik** [comment]
I had the same problem:

```console
$ sudo npx mira refresh
/opt/homebrew/lib/node_modules/boox-mira/node_modules/node-hid/nodehid.js:49
    this._raw = new (Function.prototype.bind.apply(binding.HID,
                ^

TypeError: cannot open device with vendor id 0x416 and product id 0x5020
    at new HID (/opt/homebrew/lib/node_modules/boox-mira/node_modules/node-hid/nodehid.js:49:17)
    at Mira.create (file:///opt/homebrew/lib/node_modules/boox-mira/src/mira.js:48:20)
    at file:///opt/homebrew/lib/node_modules/boox-mira/bin/cli.js:7:19
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v19.1.0
```

The device is connected via usb:

<img width="376" alt="image" src="https://user-images.githubusercontent.com/52673/208954037-af05c114-ea59-44b4-86d0-9e706d676a86.png">


<img width="590" alt="image" src="https://user-images.githubusercontent.com/52673/208954460-652609f8-694b-406b-870b-b06df176753a.png">

---

But when I quit the mira GUI app, the CLI tool can talk to the device.
