### ISSUE TITLE
Error appears (configuration property 'app.name')

### ISSUE THREAD

**Issue by JavaDevUa** [ipodnerd3019/mira-js#5]
When I run any command, for example `npx mira --help`, I get an error. Here is the stacktrace:
`$ npx mira --help
WARNING: No configurations found in configuration directory:/etc/udev/rules.d/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
Configuration property "app.name" is not defined, you will not be able to deploy your app yet. 

/home/pros/.npm/_npx/d4f9699003e8999f/node_modules/config/lib/config.js:182
    throw new Error('Configuration property "' + property + '" is not defined');
          ^
Error: Configuration property "app.name" is not defined
    at Config.get (/home/pros/.npm/_npx/d4f9699003e8999f/node_modules/config/lib/config.js:182:11)
    at new MiraConfigClass (/home/pros/.npm/_npx/d4f9699003e8999f/node_modules/mira/src/config/mira-config.ts:121:50)
    at Object.<anonymous> (/home/pros/.npm/_npx/d4f9699003e8999f/node_modules/mira/src/config/mira-config.ts:275:27)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Function.Module._load (node:internal/modules/cjs/loader:838:12)
    at Module.require (node:internal/modules/cjs/loader:1021:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/pros/.npm/_npx/d4f9699003e8999f/node_modules/mira/src/cdk/stack.ts:7:1)`

P.S. I followed 'Linux notes' too
P.P.S. I used archlinux; Mira Software from official vendor doesn't detect my display. I am connected with HDMI + TypeC. Monitor (mira) works. 
P.P.S. You are doing an important job. I am ready to assist in any search of issue. If you would like anything from me, answer in this comment section, I will respond and provide whatever needed

**Comment by ipodnerd3019** [comment]
It looks like you have installed https://www.npmjs.com/package/mira instead of https://www.npmjs.com/package/boox-mira.

Make sure you are installing with `npm install -g boox-mira`.
