### ISSUE TITLE
error: unexpected reserved word?

### ISSUE THREAD

**Issue by derekvan** [ipodnerd3019/mira-js#6]
I'm getting the following error on `npx Mira refresh` and `npx Mira settings`

````
(node:85783) ExperimentalWarning: The ESM module loader is experimental.
file:///usr/local/lib/node_modules/boox-mira/bin/cli.js:13
await yargs(hideBin(process.argv))
^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:122:18)
    at async link (internal/modules/esm/module_job.js:42:21)
````

**Comment by ipodnerd3019** [comment]
You are probably using an old version of Node. I recommend updating to the latest stable version >= 16.
